config:
  #로어커맨드가 실행되지 않을 아이템 코드를 적습니다.
  RejectItemCode:
    - '368'
  #로어 커맨드가 적용되는 아이템들은 꼭 Displayname을 가지고 있어야 합니다. (Displayname 이란 아이템 고유의 이름을 말합니다.)
  
  a:
    lore: '절강'
    cooldown: 5
    hunger: 0
    sharecooldown: 0
    consume: 'yes'
    right: true
    world:
      - 'world'
      - 'world_nether'
    commands:
      - 'lightning'
      - 'fireball'
  b:
    lore: 'ㅇㅇ'
    cooldown: 5
    hunger: 0
    sharecooldown: 0
    consume: 'yes'
    right: false
    world:
      - 'world'
    commands:
      - 'fireball'