name: LoreCommand
main: com.Moon_Eclipse.lorecommand.lorecommand
version: 1.2v[05.04]
author: Moon_Eclipse(MCMANY Mincraft Manyserver)

commands:
  lorecommand:
    description: /lorecommand reload
