config:
  SpawnLocation: world,111,222,333
  ArcadeJumpLocation: 35,72,-21:70,140,50
  Law:
  - §0§l [마인 아레나 서버 법전]§0<l><l><l><l><l><l><l><l><l>§9[주의 사항]            2 page<l>§9[채팅관련 법규]        3 page<l>§9[아레나 관련 법규]     8 page<l>§9[파쿠르 관련 법규]     9 page<l>§9[배심원 관련 법규]    10 page<l>
  - §4§l       [주의 사항]§0<l>   <l>§4§n처벌을 받는 몇몇 유저가 처벌을 하려하면 나가거나, 규칙에 어긋나는 행동을 하고 접속 종료 및 처벌을 받아도 상관없다는 등의 항의 발언을 하는 경우가 있습니다. 위와 같은 행동이나 발언 등을 할 경우 1단계 더 강한 처벌을 드립니다.<l>ex) 뮤트10분 -> 1시간<l>    밴 5시간 -> 1일
  - '§4§l         [채팅]§0<l>   <l>도배(특수기호, 같은말 반복):<l>§9 - 1회 뮤트 10분<l>§a - 2회 뮤트 1시간<l>§c
    - 3회 뮤트 1일<l>   <l>§0타서버 발언: §9영구 뮤트<l> §c- 사과문 작성시 1일뮤트<l>   <l>§0타서버 홍보: §9영구
    밴<l>§c - 타서버에서 우리서버를<l>   홍보해도 마찬가지 입니다.<l>'
  - 타서버 발언의 정의:<l>§9타서버의 이름, 서버주소, 카페주소, 컨텐츠를 포함하지않는 타서버에 관한 이야기를 한 경우.<l>   <l>§0타서버 홍보의 정의:<l>§9타서버의 이름, 서버주소, 카페주소, 컨텐츠중 1가지라도 포함된 말을 한 경우.
  - '성드립, 패드립:<l>§9 - 1회 뮤트 10분<l>§a - 2회 뮤트 1시간<l>§c - 3회 뮤트 1일<l>   <l>§0어택협박: §9아이피밴,
    밴<l>   <l>§0오피, 어드민, 서버 비하 발언:<l>§9 - 1000년 뮤트<l>   <l>§0오피,아이템 구걸:<l>§9 - 1회
    뮤트 10분<l>§a - 2회 뮤트 1시간<l>§c - 3회 뮤트 1일'
  - '욕설:<l>§9 - 1회 뮤트 10분<l>§a - 2회 뮤트 1시간<l>§c - 3회 뮤트 1일<l>   <l>§0상대방을 기분나쁘게 하는<l> 말, 말투:<l>§9 - 1회 뮤트 10분<l>§a - 2회 뮤트 1시간<l>§c - 3회 뮤트 1일<l>§c(특정 상황에서의 기분나쁜 말은 앞뒤 내용을 파알할 수 있는 스샷이 필요합니다.)'
  - '상대방을 기분나쁘게 하는 말, 말투의 예시:<l>§9[간단하게 이겼네 ㅋㅋ]<l>[별거 아니네; 왜깝치지] §0등 <l>   <l>§c처벌을
    내리는 배심원이 봤을때 기분 나쁜 언행이라면 뮤트 가능하게 했습니다.<l>   <l>§0닉네임 사칭: §9밴<l>§a(/ban 닉네임 사유)<l>§c[!사유를
    꼭 적어주세요!]<l>   <l>§0어드민 사칭: §9아이피밴'
  - §4§l        [아레나]§0<l>   <l>싸움중 시간 끌기:<l>§9 - 처벌 없음<l>   <l>§0패작:<l>§9 - 영구 밴
  - '§4§l        [파쿠르]§0<l>   <l>서로간의 방해: §9가능'
  - §4§l        [배심원]§0<l>   <l>위 처벌 목록대로 벌하지 않을 경우, 적절한 사유를 설명하지 못할시 배심원 강등 및 3일 밴을 드립니다.<l><l>*밴을 할때는 밴 사유를 꼭 적어서 밴합니다.<l>§9 - ex) /ban asd123 팜테러<l><l>§0처벌 중첩 기준:<l>§9 - 오전 12시 기준 초기화
  - §9- ex) 2017-02-28 15:28분 <l>채팅 도배한 유저A의 처벌은 2017-03-01 00:00에 초기화함.<l><l>§c처벌을 한 뒤에 꼭 오픈 채팅방에 적어 주셔야 합니다. 적지 않으면 불이익이 생길 수 있으니 주의 바랍니다.'
  JumpBlock:
  - ''
  GameTime: 90
  DecreateScore: 10
  InCreaseScore:
  - '13'
  - '14'
  - '15'
  CanNotNominateInMatch:
  - kick
  CanNotUseInMatch:
  - back
  - tpa
  FieldIcon:
    id: 431
    meta: 0
    name: §7=== §a필드 아레나 입장 §7===
    lore:
    - §f
    - §a▶ §f클릭 시 §a필드 아레나 §f에 입장합니다.
    - §a▶ §f하나의 필드에 모든 유저들이 모입니다.
    - §a▶ §f목적없이 죽고 죽이는 §4살육전§f을 지금 시작하세요!
    - §f
    - §b▶ §f드넓은 땅에서 §4<FieldKillCount>§f명의 목숨을 끊었습니다!
  DefaultIcon:
    id: 324
    meta: 0
    name: §7=== §e일반 아레나 입장 §7===
    lore:
    - §f
    - §a▶ §f클릭 시 §e일반 아레나 §f매칭을 시작합니다.
    - §a▶ §3랭크 포인트(RP)§f와 상관없이 상대가 매칭되며
    - §a▶ §b승리§f시 §e30골드§f를, §c패배§f시 §e10골드§f를 얻습니다.
    - §a▶ §f또한 §b3승§f마다 §5일반 아레나 복권§f을 추가로 얻습니다.
    - §f
    - §b▶ §f일반 아레나에서 §4<DefaultWinCount>§f명에게 §e10골드§f를 선물했습니다!
  CompititionIcon:
    id: 330
    meta: 0
    name: §7=== §b랭크 아레나 입장 §7===
    lore:
    - §f
    - §a▶ §f클릭 시 §b랭크 아레나 §f매칭을 시작합니다.
    - §a▶ §3랭크 포인트(RP)§f가 비슷한 상대와 매칭되며
    - §a▶ §b승리§f시 §e30골드§f와 §5아레나 복권§f을, §c패배§f시 §e10골드§f를 얻습니다.
    - §a▶ §f지급되는 §b전리품§f은 §3랭크 포인트§f에 따라 차등 지급됩니다.
    - §f
    - '§b▶ §f현재 랭크 포인트: §f【 §e<CompititionPoint>§3RP §f】'
    - '§b▶ §f당신은 현재 상위 <RankingPercentString>% 유저 입니다.'
    
    - §b▶ §f이때까지 §4<CompititionWinCount>§f명의 점수를 떨어트렸습니다!
