config:
  name:
    - '&a[E] &7좀비 보주'
    - '&2[X]능력을 흡수한 구슬'
    - '&5[보주] &f파괴의 보주'
  drawitemname:
    - '&2[X]정화의 구슬'
  DrawOutName: '&2[X]능력을 흡수한 구슬'
  RemoveItem:
    - '&2[X]마녀의 구슬'
  ExRemoveItem:
    - '&2[X]현자의 구슬'
  SoketString: '&f〔 &b추가 능력치: &7없음 &f〕'
  ExSoketString: '&f〔 &b추가 능력치: &7없음 &f〕'
  getlorenum: 4
  Helmet: '머리'
  chest: '몸통'
  leggings: '다리'
  boots: '발'
  weapons: '무기'
  shield: '방패'
  pickaxe: '곡괭이'
  searchword: '추가'
  drawsearchword: '〕'
  prefix: '&b[마인아레나]&e '
  HelmetId:
    - '298'
    - '302'
    - '306'
    - '310'
    - '314'
  ChestId:
    - '299'
    - '303'
    - '307'
    - '311'
    - '315'
    - '443'
  LeggingsId:
    - '300'
    - '304'
    - '308'
    - '312'
    - '316'
  BootsId:
    - '301'
    - '305'
    - '309'
    - '313'
    - '317'
  ShieldId:
    - '442'
  WeaponsId:
    - '267'
    - '268'
    - '272'
    - '276'
    - '283'
    - '258'
    - '271'
    - '275'
    - '279'
    - '286'
    - '261'
    - '256'
    - '290'
    - '269'
    - '291'
    - '273'
    - '292'
    - '277'
    - '293'
    - '284'
    - '294'
    - '257'
    - '270'
    - '274'
    - '278'
    - '285'
    - '346'